version: '2'
services:
  queue-consumer:
    depends_on:
      - restmq
      - webdis
    environment:
      - RESTMQ_URL=http://restmq:8888/
      - WEBDIS_URL=http://webdis:7379/

  queue-loader:
    depends_on:
      - restmq
      - webdis
    ports:
      - "8000:3000"
    environment:
      - RESTMQ_URL=http://restmq:8888/

  queue-result:
    depends_on:
      - webdis
    ports:
      - "8001:3000"
    environment:
      - WEBDIS_URL=http://webdis:7379/

  
  webdis:
    image: anapsix/webdis
    environment:
      - LOCAL_REDIS=true

  restmq:
    image: pablozaiden/restmq
